# Generated by Django 5.0.7 on 2024-08-26 05:27

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import home.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='YearlyCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('total_businesses', models.IntegerField(default=0)),
                ('total_collection', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('annual_collection', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('bi_annual_collection', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('quarterly_collection', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('extension_name', models.CharField(max_length=50)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Staff_user',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('home.user',),
            managers=[
                ('user', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_no', models.CharField(max_length=100)),
                ('business_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('extension_name', models.CharField(blank=True, max_length=10, null=True)),
                ('gender', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('application_date', models.DateField()),
                ('application_type', models.CharField(max_length=100)),
                ('capital_investment', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('gross_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('business_nature', models.CharField(max_length=255)),
                ('plate_no', models.CharField(max_length=100)),
                ('date_issued', models.DateField(blank=True, null=True)),
                ('telephone_no', models.CharField(blank=True, max_length=15, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=15, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('application_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.applicationmethod')),
                ('business_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.businesstype')),
                ('payment_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.paymentmode')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('or_no', models.CharField(max_length=20, unique=True)),
                ('business_no', models.CharField(max_length=100)),
                ('business_name', models.CharField(max_length=255)),
                ('payor', models.CharField(max_length=255)),
                ('business_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('permit', models.CharField(blank=True, max_length=100, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('linked_business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.business')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('paid_count', models.IntegerField(default=0)),
                ('not_paid_count', models.IntegerField(default=0)),
                ('annual_paid_count', models.IntegerField(default=0)),
                ('bi_annual_paid_count', models.IntegerField(default=0)),
                ('quarterly_paid_count', models.IntegerField(default=0)),
                ('annual_count', models.IntegerField(default=0)),
                ('bi_annual_count', models.IntegerField(default=0)),
                ('quarterly_count', models.IntegerField(default=0)),
                ('total_collection', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('annual_collection', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('bi_annual_collection', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('quarterly_collection', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
            ],
            options={
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to=home.models.get_upload_to)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.business')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='years', to='home.business')),
            ],
            options={
                'unique_together': {('business', 'year')},
            },
        ),
    ]
