# Generated by Django 5.0.7 on 2024-09-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_userlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogs',
            name='pictures',
            field=models.ManyToManyField(blank=True, to='home.picture'),
        ),
    ]
