# Generated by Django 5.0.7 on 2024-12-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_userlogs_latitude_userlogs_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='business_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
