# Generated by Django 5.0.7 on 2024-12-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_adminmessage_delete_botmessage_delete_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmessage',
            name='status',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
