# Generated by Django 5.0.7 on 2024-12-26 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_adminmessage_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminmessage',
            old_name='status',
            new_name='sent_status',
        ),
    ]
