# Generated by Django 5.0.7 on 2024-12-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_status_adminmessage_sent_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmessage',
            name='sent_status',
            field=models.BooleanField(default=False),
        ),
    ]
