# Generated by Django 5.0.7 on 2024-12-27 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_adminmessage_sent_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessYear',
        ),
    ]
