# Generated by Django 5.0.7 on 2024-12-28 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_delete_businessyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='years', to='home.business')),
            ],
            options={
                'unique_together': {('business', 'year')},
            },
        ),
    ]
