# Generated by Django 5.0.7 on 2024-12-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_business_latitude_alter_business_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='business_no',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
